name: Node.js CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      dynamodb-local:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
      - run: npm test
      - run: npm run ts-check
      - run: npm run js-check
      - run: npm run lint
